version: "2"

services:
    nginx:

    app:
        build: ./
        volumes:
            - ./:/usr/src/app
        ports:
            - "8443:8443"
        links:
            - mongodb
        environment:
            - API_KEY
            - API_SECRET
            - WS_PORT
            - HTTP_PORT
            - MONGODB_USER
            - MONGODB_PASS
            - MONGODB_HOST
            - MONGODB_PORT
            - MONGODB_NAME
            - SSL_KEY=/usr/src/app/certs/key.pem
            - SSL_CERT=/usr/src/app/certs/cert.pem
            - SSL_CA=/usr/src/app/certs/ca-bundle
    mongodb:
        image: mongo
        expose:
            - "3306"
        volumes:
            - /var/lib/mongo:/data/db
        ports:
            - "27017:27017"
        environment:
            - MONGODB_USER
            - MONGODB_PASS
            - MONGODB_NAME
        command: --auth
