version: "2"

services:
    app:
        build: ./
        volumes:
            - ./:/usr/src/app
        ports:
            - "8443:8443"
        links:
            - mongodb
        environment:
            - API_KEY
            - API_SECRET
            - WS_PORT
            - HTTP_PORT
            - SSL_KEY=/usr/src/app/certs/key.pem
            - SSL_CERT=/usr/src/app/certs/cert.pem
            - SSL_CA=/usr/src/app/certs/ca-bundle
